const express = require('express');
const router = express.Router();
const Loyalty = require('../models/Loyalty');
const { protect, authorise } = require('../middleware/auth');
const { getSetting, updateSetting, lookupWallet } = require('../controllers/loyaltyController');
const { settleLoyalty, finalizeAccrual } = require('../controllers/loyaltySettlementController');
router.get('/', protect, async (req,res)=>{try{const filter=req.query.customerId?{customer_id:req.query.customerId}:{};const history=await Loyalty.find(filter).populate('franchise_id','name franchiseCode').sort({createdAt:-1}).limit(50);res.json({success:true,history})}catch(e){res.status(500).json({success:false,message:e.message})}});
router.get('/settings', protect, authorise('master_admin','pos_staff','shift_operator','manager','franchise_owner'), getSetting);
router.put('/settings', protect, authorise('master_admin'), updateSetting);
router.get('/wallet', protect, authorise('pos_staff','shift_operator','manager','franchise_owner'), lookupWallet);
router.post('/sessions/:sessionId/redeem', protect, authorise('pos_staff','shift_operator','manager','franchise_owner'), settleLoyalty);
router.post('/sessions/:sessionId/finalize', protect, authorise('pos_staff','shift_operator','manager','franchise_owner'), finalizeAccrual);
module.exports = router;
