import { useState, useEffect } from 'react';
import { X, Banknote, CreditCard, Smartphone, Wallet, Plus, CheckCircle2, Loader2, IndianRupee, AlertCircle, Star } from 'lucide-react';
import api from '../../lib/api';
import toast from 'react-hot-toast';
const METHODS=[{id:'Cash',label:'Cash',Icon:Banknote,color:'text-green-400',bg:'bg-green-400/10',border:'border-green-500/30'},{id:'UPI',label:'UPI',Icon:Smartphone,color:'text-blue-400',bg:'bg-blue-400/10',border:'border-blue-500/30'},{id:'Card',label:'Card',Icon:CreditCard,color:'text-purple-400',bg:'bg-purple-400/10',border:'border-purple-500/30'},{id:'Net Banking',label:'Net Banking',Icon:CreditCard,color:'text-cyan-400',bg:'bg-cyan-400/10',border:'border-cyan-500/30'},{id:'Wallet',label:'Wallet',Icon:Wallet,color:'text-orange-400',bg:'bg-orange-400/10',border:'border-orange-500/30'},{id:'Loyalty Points',label:'Loyalty',Icon:Star,color:'text-amber-400',bg:'bg-amber-400/10',border:'border-amber-500/30'}];
const fmt=n=>`₹${Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function SplitPaymentModal({sessionId,totalAmount,franchiseId,onSuccess,onClose}){
 const[entries,setEntries]=useState([]),[paidTotal,setPaidTotal]=useState(0),[method,setMethod]=useState('Cash'),[amount,setAmount]=useState(''),[reference,setReference]=useState(''),[adding,setAdding]=useState(false),[done,setDone]=useState(false),[upiQr,setUpiQr]=useState(null),[upiLoading,setUpiLoading]=useState(false),[loyalty,setLoyalty]=useState({points:0,pointsValue:0});
 const API=import.meta.env.VITE_API_URL||'https://utc-cafe.onrender.com/api';
 useEffect(()=>{if(!sessionId)return;api.get(`/sessions/${sessionId}`).then(async r=>{const s=r.data.session||r.data;setPaidTotal(s.paidAmount||0);if(s.customerMobile){try{const w=await api.get(`/loyalty/wallet?phone=${s.customerMobile}`);setLoyalty({points:w.data.points||0,pointsValue:w.data.pointsValue||0})}catch{}}}).catch(()=>{})},[sessionId]);
 useEffect(()=>{const amt=parseFloat(amount);if(method!=='UPI'||!amt||!franchiseId){setUpiQr(null);return}setUpiLoading(true);fetch(`${API}/public/upi-qr/${franchiseId}?amount=${amt.toFixed(2)}&sessionId=${sessionId}`).then(r=>r.json()).then(d=>{if(d.success&&d.qr)setUpiQr(d)}).catch(()=>{}).finally(()=>setUpiLoading(false))},[method,amount,franchiseId,sessionId]);
 const remaining=Math.max(0,totalAmount-paidTotal);const overpaid=paidTotal>totalAmount;const fillRemaining=()=>setAmount(remaining.toFixed(2));
 const addPayment=async()=>{const amt=parseFloat(amount);if(method==='Loyalty Points'){const pointValue=loyalty.points?loyalty.pointsValue/loyalty.points:0;if(!pointValue){toast.error('No loyalty points available');return}const pts=Math.min(loyalty.points,Math.floor(amt||0));if(!pts){toast.error('Enter points to redeem');return}setAdding(true);try{const res=await api.post(`/loyalty/sessions/${sessionId}/redeem`,{points:pts});const value=Number(res.data.redemptionValue||0);const newPaid=Number(res.data.session?.paidAmount||paidTotal+value);setPaidTotal(newPaid);setEntries(p=>[...p,{method,amount:value,reference:`${res.data.appliedPoints} pts`}]);setAmount('');setLoyalty(p=>({points:Math.max(0,p.points-Number(res.data.appliedPoints||0)),pointsValue:Math.max(0,p.pointsValue-value)}));if(res.data.session?.paymentStatus==='fully_paid'){setDone(true);setTimeout(()=>onSuccess({invoice:res.data.invoice,session:res.data.session}),300)}else toast.success(`${res.data.appliedPoints} points redeemed · ${fmt(value)}`)}catch(err){toast.error(err.response?.data?.message||'Loyalty redemption failed')}finally{setAdding(false)}return}
 if(!amt||amt<=0){toast.error('Enter a valid amount');return}if(amt>remaining+.01){toast.error(`Amount exceeds remaining balance of ${fmt(remaining)}`);return}setAdding(true);try{const res=await api.post(`/sessions/${sessionId}/payment`,{amount:amt,method,reference:reference.trim()||''});const newPaid=res.data.session?.paidAmount??paidTotal+amt;setPaidTotal(newPaid);setEntries(p=>[...p,{method,amount:amt,reference:reference.trim()}]);setAmount('');setReference('');if(res.data.session?.paymentStatus==='fully_paid'){await api.post(`/loyalty/sessions/${sessionId}/finalize`);setDone(true);toast.success('Payment complete!');setTimeout(()=>onSuccess({invoice:res.data.invoice,session:res.data.session}),300)}else{const bal=res.data.balance??totalAmount-newPaid;toast.success(`${fmt(amt)} recorded · Remaining: ${fmt(bal)}`)}}catch(err){toast.error(err.response?.data?.message||'Payment failed')}finally{setAdding(false)}};
 const selectedMethod=METHODS.find(m=>m.id===method);
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-sm p-4"><div className="bg-dark-800 border border-dark-600 rounded-2xl w-full max-w-md shadow-2xl flex flex-col max-h-[90vh] overflow-y-auto">
 <div className="flex items-center justify-between p-5 border-b border-dark-600 shrink-0"><div><h2 className="text-white font-bold flex items-center gap-2"><IndianRupee size={18} className="text-brand-400"/> Split Payment</h2><p className="text-xs text-gray-500 mt-0.5">Accept multiple payment methods including loyalty points</p></div>{!done&&<button onClick={onClose} className="text-gray-500 hover:text-white"><X size={18}/></button>}</div>
 <div className="px-5 py-4 border-b border-dark-600 grid grid-cols-3 gap-3 text-center shrink-0"><div><div className="text-xs text-gray-500 mb-1">Bill Total</div><div className="text-white font-mono font-semibold text-sm">{fmt(totalAmount)}</div></div><div><div className="text-xs text-gray-500 mb-1">Paid</div><div className="text-green-400 font-mono font-semibold text-sm">{fmt(paidTotal)}</div></div><div><div className="text-xs text-gray-500 mb-1">Remaining</div><div className={`font-mono font-semibold text-sm ${remaining===0?'text-green-400':'text-yellow-400'}`}>{fmt(remaining)}</div></div></div>
 {loyalty.points>0&&<div className="mx-5 mt-3 rounded-xl border border-amber-500/30 bg-amber-500/10 px-3 py-2"><div className="flex justify-between text-xs text-amber-300 font-bold"><span>★ Loyalty Wallet</span><span>{loyalty.points} pts</span></div><div className="text-[10px] text-amber-200/70 mt-0.5">Available redemption value: {fmt(loyalty.pointsValue)} · No cash required</div></div>}
 <div className="px-5 pt-3 pb-0 shrink-0"><div className="h-2 bg-dark-700 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-brand-500 to-green-500 rounded-full transition-all" style={{width:`${Math.min(100,(paidTotal/totalAmount)*100)}%`}}/></div></div>
 {entries.length>0&&<div className="px-5 pt-3 space-y-2"><div className="text-xs text-gray-500 font-medium uppercase tracking-wide">Transactions</div>{entries.map((e,i)=>{const m=METHODS.find(x=>x.id===e.method);return <div key={i} className={`flex items-center justify-between px-3 py-2 rounded-xl border ${m?.border} ${m?.bg}`}><div className="flex items-center gap-2">{m&&<m.Icon size={14} className={m.color}/>}<span className={`text-sm font-medium ${m?.color}`}>{e.method}</span>{e.reference&&<span className="text-xs text-gray-500 font-mono">{e.reference}</span>}</div><div className="flex items-center gap-2"><span className="text-white font-mono text-sm">{fmt(e.amount)}</span><CheckCircle2 size={14} className="text-green-400"/></div></div>})}</div>}
 {!done&&remaining>0&&<div className="px-5 pt-4 pb-5 space-y-3 border-t border-dark-600 mt-3 shrink-0"><div className="grid grid-cols-3 sm:grid-cols-6 gap-1.5">{METHODS.map(m=><button key={m.id} onClick={()=>{setMethod(m.id);setAmount('')}} className={`flex flex-col items-center gap-1 py-2 rounded-xl border text-xs font-medium transition-all ${method===m.id?`${m.bg} ${m.border} ${m.color}`:'border-dark-500 bg-dark-700 text-gray-500 hover:text-white'}`}><m.Icon size={14}/><span className="text-[9px] leading-tight text-center">{m.label}</span></button>)}</div>
 {method==='Loyalty Points'?<div className="space-y-2"><label className="block text-xs text-amber-300">Points to redeem (max {loyalty.points})</label><div className="flex gap-2"><input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Points" className="flex-1 bg-dark-700 border border-dark-500 text-white text-sm rounded-xl px-3 py-2.5"/><button onClick={()=>setAmount(String(Math.min(loyalty.points,Math.floor(remaining/(loyalty.pointsValue/Math.max(1,loyalty.points))))))} className="px-3 bg-dark-700 border border-dark-500 text-gray-400 rounded-xl text-xs">MAX</button></div><div className="text-[10px] text-gray-500">Value covered: {fmt(Math.min(Number(amount||0)*(loyalty.pointsValue/Math.max(1,loyalty.points)),remaining))}</div></div>:<><div><div className="flex gap-2"><div className="relative flex-1"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">₹</span><input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" className="w-full bg-dark-700 border border-dark-500 text-white text-sm rounded-xl pl-7 pr-3 py-2.5"/></div><button onClick={fillRemaining} className="px-3 bg-dark-700 border border-dark-500 text-gray-400 rounded-xl text-xs">Full {fmt(remaining)}</button></div></div>{method==='UPI'&&<div className="flex flex-col items-center gap-2 py-3 border border-blue-500/20 rounded-xl bg-blue-500/5">{upiLoading&&<Loader2 size={24} className="animate-spin text-blue-400"/>}{upiQr&&!upiLoading&&<><div className="text-xs font-bold text-blue-400">SCAN TO PAY ₹{parseFloat(amount||0).toFixed(2)}</div><img src={upiQr.qr} alt="UPI QR" className="w-32 h-32 border border-gray-300 rounded-lg"/><div className="text-[10px] text-gray-400">{upiQr.upiId}</div></>}{!upiQr&&!upiLoading&&amount&&<div className="text-xs text-gray-500">Enter amount above to generate QR</div>}</div>}{['UPI','Card','Net Banking'].includes(method)&&<input type="text" value={reference} onChange={e=>setReference(e.target.value)} placeholder={method==='Card'?'Last 4 digits':'Reference / TXN ID'} className="w-full bg-dark-700 border border-dark-500 text-white text-sm rounded-xl px-3 py-2.5"/>}</>}
 <button onClick={addPayment} disabled={adding||!amount} className={`w-full flex items-center justify-center gap-2 py-3 text-sm font-semibold rounded-xl transition-colors disabled:opacity-50 ${selectedMethod?`${selectedMethod.bg} ${selectedMethod.border} border ${selectedMethod.color}`:'bg-brand-500 text-white'}`}>{adding?<Loader2 size={16} className="animate-spin"/>:<Plus size={16}/>} Record {method} Payment</button></div>}
 {done&&<div className="flex flex-col items-center gap-3 py-8 px-5"><div className="w-16 h-16 rounded-full bg-green-500/20 flex items-center justify-center"><CheckCircle2 size={32} className="text-green-400"/></div><div className="text-white font-bold text-lg">Payment Complete!</div><div className="text-sm text-gray-500 text-center">{entries.length} transaction{entries.length!==1?'s':''} recorded · Total {fmt(totalAmount)}</div></div>}
 {overpaid&&!done&&<div className="mx-5 mb-4 flex items-center gap-2 bg-orange-500/10 border border-orange-500/30 rounded-xl px-3 py-2 text-xs text-orange-400"><AlertCircle size={14}/> Change to return: {fmt(paidTotal-totalAmount)}</div>}
 </div></div>;
}
